import streamlit as st
from resume_reader import read_pdf, read_docx, extract_keywords
# Import our NEW AI question generator
from question_generator import generate_questions_with_ai, generate_behavioral_questions, generate_situational_questions, speak_question
from evaluator import calculate_job_fit, evaluate_response
import os

# --- App State Management (No changes here) ---
if 'interview_started' not in st.session_state:
    st.session_state.interview_started = False
if 'current_question_index' not in st.session_state:
    st.session_state.current_question_index = 0
if 'answers' not in st.session_state:
    st.session_state.answers = []
if 'all_questions' not in st.session_state:
    st.session_state.all_questions = []
if 'report_generated' not in st.session_state:
    st.session_state.report_generated = False

# --- UI Layout ---
st.set_page_config(layout="wide")
st.title("🚀 True AI Interview Coach (Powered by Generative AI)")
st.markdown("Experience a truly realistic interview. The AI will analyze the **entire context** of your resume and the job description to ask difficult, human-like questions.")

# --- Sidebar for Inputs ---
with st.sidebar:
    st.header("1. Interview Setup")
    
    sample_resume_path = os.path.join("assets", "sample_resume.pdf")
    sample_jd_path = os.path.join("assets", "sample_job_description.txt")
    
    use_sample_files = st.checkbox("Use Sample Files for Demonstration", value=True)
    
    uploaded_resume = None
    job_description = ""

    if use_sample_files:
        try:
            with open(sample_resume_path, "rb") as f: uploaded_resume = f
            with open(sample_jd_path, "r") as f: job_description = f.read()
            st.info("Sample resume and job description loaded.")
        except FileNotFoundError:
            st.error("Sample files not found in 'assets' folder.")
    else:
        uploaded_resume = st.file_uploader("Upload Your Resume (PDF or DOCX)", type=["pdf", "docx"])
        job_description = st.text_area("Paste the Full Job Description Here", height=250)

    st.markdown("---")
    st.header("2. Question Configuration")
    # We now call the AI for the technical questions.
    num_technical_ai = st.slider("Number of AI-Generated Technical Questions", 0, 10, 5)
    num_behavioral = st.slider("Number of Behavioral Questions", 0, 10, 3)
    num_situational = st.slider("Number of Situational Questions", 0, 10, 2)
    
    st.markdown("---")
    if st.button("🤖 Start AI-Powered Interview", disabled=st.session_state.interview_started, type="primary"):
        if (uploaded_resume or use_sample_files) and job_description:
            with st.spinner("The AI is reading your resume and crafting challenging questions... This may take a moment."):
                resume_text = ""
                if use_sample_files:
                    with open(sample_resume_path, "rb") as f:
                        resume_text = read_pdf(f) if sample_resume_path.endswith(".pdf") else ""
                elif uploaded_resume:
                    resume_text = read_pdf(uploaded_resume) if uploaded_resume.type == "application/pdf" else read_docx(uploaded_resume)
                
                # --- THIS IS THE NEW LOGIC ---
                # Call the AI to get the best questions possible.
                tech_questions = generate_questions_with_ai(resume_text, job_description, num_technical_ai)
                behav_questions = generate_behavioral_questions(num_behavioral)
                sit_questions = generate_situational_questions(num_situational)
                
                st.session_state.all_questions = tech_questions + behav_questions + sit_questions
                st.session_state.answers = [""] * len(st.session_state.all_questions)
                st.session_state.resume_text = resume_text
                st.session_state.job_description = job_description
                st.session_state.interview_started = True
                st.session_state.current_question_index = 0
                st.session_state.report_generated = False
                st.rerun()
        else:
            st.warning("Please provide a resume and job description to begin.")

# --- The rest of the app (interview and report) remains the same ---
# It will simply display the higher-quality questions generated by the AI.
# (No changes needed to the code below this line)

if st.session_state.interview_started and not st.session_state.report_generated:
    st.header("🎙️ Interview in Progress")
    total_questions = len(st.session_state.all_questions)
    current_q_num = st.session_state.current_question_index + 1
    
    st.progress(current_q_num / total_questions, text=f"Question {current_q_num} of {total_questions}")
    
    current_question = st.session_state.all_questions[st.session_state.current_question_index]
    
    col1, col2 = st.columns([4, 1])
    with col1:
        st.subheader(f"Question {current_q_num}:")
        st.markdown(f"### *{current_question}*")
    with col2:
        if st.button("▶️ Read Aloud", help="Click to have the question read to you."):
            speak_question(current_question)

    st.session_state.answers[st.session_state.current_question_index] = st.text_area("Your Answer", key=f"answer_{st.session_state.current_question_index}", height=250)

    col1, col2, col3 = st.columns([1, 6, 1])
    with col1:
        if st.button("⬅️ Previous", disabled=(st.session_state.current_question_index == 0)):
            st.session_state.current_question_index -= 1; st.rerun()
    with col3:
        if st.session_state.current_question_index < total_questions - 1:
            if st.button("Next ➡️"):
                st.session_state.current_question_index += 1; st.rerun()
        else:
            if st.button("Finish & See Report", type="primary"):
                st.session_state.report_generated = True; st.rerun()

if st.session_state.report_generated:
    st.header("🏆 Your Detailed Performance Report")
    with st.spinner("Generating your detailed feedback..."):
        resume_keywords = extract_keywords(st.session_state.resume_text)
        jd_keywords = extract_keywords(st.session_state.job_description)
        st.subheader("1. Job Fit Analysis: Resume vs. Job Description")
        job_fit_score, common_keywords, missing_keywords = calculate_job_fit(resume_keywords, jd_keywords)
        st.metric(label="Resume-to-Job-Description Match Score", value=f"{job_fit_score:.2f}%")
        st.progress(int(job_fit_score))
        if job_fit_score < 50:
            st.warning(f"**Area for Improvement:** Consider tailoring your resume by including some of the missing keywords below.", icon="⚠️")
        else:
            st.success(f"**Strong Alignment:** Your resume has a strong keyword match with the job description.", icon="✅")
        col1, col2 = st.columns(2)
        with col1:
            st.markdown("**✅ Keywords Found in Your Resume:**"); st.write(", ".join(sorted(common_keywords)))
        with col2:
            st.markdown("**❌ Keywords Missing From Your Resume:**"); st.write(", ".join(sorted(missing_keywords)))
        st.markdown("---")
        st.subheader("2. Question-by-Question Performance Breakdown")
        total_score = 0
        for i, (question, answer) in enumerate(zip(st.session_state.all_questions, st.session_state.answers)):
            with st.expander(f"**View Analysis for Question {i+1}:** {question[:60]}..."):
                st.markdown(f"***Your Answer:***"); st.info(f"{answer if answer.strip() else 'No answer was provided.'}")
                score, feedback = evaluate_response(answer, jd_keywords)
                total_score += score
                st.markdown(f"***Detailed Feedback:***"); st.warning(feedback)
        st.markdown("---")
        st.subheader("3. Final Assessment and Recommendations")
        avg_performance = total_score / len(st.session_state.all_questions) if st.session_state.all_questions else 0
        st.metric("Average Answer Relevance Score", f"{avg_performance:.2f}%")
    if st.button("🔄 Start a New Interview"):
        for key in list(st.session_state.keys()): del st.session_state[key]
        st.rerun()